async function Module(moduleArg={}){var moduleRtn;var d=moduleArg,aa=import.meta.url,p="",q;try{p=(new URL(".",aa)).href}catch{}q=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var r=console.error.bind(console),t,u=!1,v,w,x,y,z,B,C,D,E,F,G,H=!1;
function I(){var a=J.buffer;d.HEAP8=y=new Int8Array(a);B=new Int16Array(a);d.HEAPU8=z=new Uint8Array(a);new Uint16Array(a);C=new Int32Array(a);D=new Uint32Array(a);E=new Float32Array(a);F=new Float64Array(a);G=new BigInt64Array(a);new BigUint64Array(a)}function K(a){d.onAbort?.(a);a="Aborted("+a+")";r(a);u=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");x?.(a);throw a;}var L;
async function ca(a){if(!t)try{var b=await q(a);return new Uint8Array(b)}catch{}if(a==L&&t)a=new Uint8Array(t);else throw"both async and sync fetching of the wasm failed";return a}async function da(a,b){try{var c=await ca(a);return await WebAssembly.instantiate(c,b)}catch(e){r(`failed to asynchronously prepare wasm: ${e}`),K(e)}}
async function ea(a){var b=L;if(!t)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(e){r(`wasm streaming compile failed: ${e}`),r("falling back to ArrayBuffer instantiation")}return da(b,a)}class M{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var N=a=>{for(;0<a.length;)a.shift()(d)},O=[],P=[],fa=()=>{var a=d.preRun.shift();P.push(a)},Q=!0;class ha{constructor(a){this.s=a-24}}
var R=0,ia=0,S=0,T={},U=a=>{if(!(a instanceof M||"unwind"==a))throw a;},V=a=>{v=a;Q||0<S||(d.onExit?.(a),u=!0);throw new M(a);},ja=a=>{if(!u)try{a()}catch(b){U(b)}finally{if(!(Q||0<S))try{v=a=v,V(a)}catch(b){U(b)}}},W=(a,b,c)=>{var e=z;if(!(0<c))return 0;var f=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=a.codePointAt(h);if(127>=g){if(b>=c)break;e[b++]=g}else if(2047>=g){if(b+1>=c)break;e[b++]=192|g>>6;e[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;e[b++]=224|g>>12;e[b++]=128|g>>6&63;e[b++]=128|
g&63}else{if(b+3>=c)break;e[b++]=240|g>>18;e[b++]=128|g>>12&63;e[b++]=128|g>>6&63;e[b++]=128|g&63;h++}}e[b]=0;return b-f},X=globalThis.TextDecoder&&new TextDecoder,ka=(a=0,b,c)=>{var e=z;var f=a;b=f+b;if(c)c=b;else{for(;e[f]&&!(f>=b);)++f;c=f}if(16<c-a&&e.buffer&&X)return X.decode(e.subarray(a,c));for(f="";a<c;)if(b=e[a++],b&128){var h=e[a++]&63;if(192==(b&224))f+=String.fromCharCode((b&31)<<6|h);else{var g=e[a++]&63;b=224==(b&240)?(b&15)<<12|h<<6|g:(b&7)<<18|h<<12|g<<6|e[a++]&63;65536>b?f+=String.fromCharCode(b):
(b-=65536,f+=String.fromCharCode(55296|b>>10,56320|b&1023))}}else f+=String.fromCharCode(b);return f},na=(a,b,c,e)=>{var f={string:k=>{var l=0;if(null!==k&&void 0!==k&&0!==k){for(var m=l=0;m<k.length;++m){var A=k.charCodeAt(m);127>=A?l++:2047>=A?l+=2:55296<=A&&57343>=A?(l+=4,++m):l+=3}l+=1;m=Y(l);W(k,m,l);l=m}return l},array:k=>{var l=Y(k.length);y.set(k,l);return l}};a=d["_"+a];var h=[],g=0;if(e)for(var n=0;n<e.length;n++){var ba=f[c[n]];ba?(0===g&&(g=la()),h[n]=ba(e[n])):h[n]=e[n]}c=a(...h);return c=
function(k){0!==g&&ma(g);return"string"===b?k?ka(k):"":"boolean"===b?!!k:k}(c)};d.noExitRuntime&&(Q=d.noExitRuntime);d.printErr&&(r=d.printErr);d.wasmBinary&&(t=d.wasmBinary);if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.shift()();d.ccall=na;d.cwrap=(a,b,c,e)=>{var f=!c||c.every(h=>"number"===h||"boolean"===h);return"string"!==b&&f&&!e?d["_"+a]:(...h)=>na(a,b,c,h,e)};
d.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":y[a]=b;break;case "i8":y[a]=b;break;case "i16":B[a>>1]=b;break;case "i32":C[a>>2]=b;break;case "i64":G[a>>3]=BigInt(b);break;case "float":E[a>>2]=b;break;case "double":F[a>>3]=b;break;case "*":D[a>>2]=b;break;default:K(`invalid type for setValue: ${c}`)}};
d.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return y[a];case "i8":return y[a];case "i16":return B[a>>1];case "i32":return C[a>>2];case "i64":return G[a>>3];case "float":return E[a>>2];case "double":return F[a>>3];case "*":return D[a>>2];default:K(`invalid type for getValue: ${b}`)}};d.UTF8ToString=(a,b,c)=>a?ka(a,b,c):"";d.stringToUTF8=(a,b,c)=>W(a,b,c);
var oa,ma,Y,la,J,pa={f:(a,b,c)=>{var e=new ha(a);D[e.s+16>>2]=0;D[e.s+4>>2]=b;D[e.s+8>>2]=c;R=a;ia++;throw R;},d:()=>K(""),b:()=>{Q=!1;S=0},c:(a,b)=>{T[a]&&(clearTimeout(T[a].id),delete T[a]);if(!b)return 0;var c=setTimeout(()=>{delete T[a];ja(()=>oa(a,performance.now()))},b);T[a]={id:c,u:b};return 0},e:a=>{var b=z.length;a>>>=0;if(268435456<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);a:{e=(Math.min(268435456,65536*Math.ceil(Math.max(a,e)/65536))-J.buffer.byteLength+
65535)/65536|0;try{J.grow(e);I();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},a:V},Z;
Z=await (async function(){function a(c){c=Z=c.exports;d._x9=c.i;d._malloc=c.j;d._y2=c.k;d._free=c.l;d._z3=c.m;oa=c.n;ma=c.o;Y=c.p;la=c.q;J=c.g;I();return Z}var b={a:pa};if(d.instantiateWasm)return new Promise(c=>{d.instantiateWasm(b,(e,f)=>{c(a(e,f))})});L??=d.locateFile?d.locateFile?d.locateFile("imgproc-wasm.wasm",p):p+"imgproc-wasm.wasm":(new URL("imgproc-wasm.wasm",import.meta.url)).href;return a((await ea(b)).instance)}());
(function(){function a(){d.calledRun=!0;if(!u){H=!0;Z.h();w?.(d);d.onRuntimeInitialized?.();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();O.push(b)}N(O)}}if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)fa();N(P);d.setStatus?(d.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>d.setStatus(""),1);a()},1)):a()})();H?moduleRtn=d:moduleRtn=new Promise((a,b)=>{w=a;x=b});
;return moduleRtn}export default Module;
